# Generated by Django 5.0.14 on 2026-09-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='crypto_amount',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=36, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='crypto_currency',
            field=models.CharField(blank=True, default='ETH', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='gaxtron_payment_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='tx_hash',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
